# yaml-language-server: $schema=https://aka.ms/dsc/schemas/v3/bundled/config/document.json
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
metadata:
  Microsoft.DSC:
    securityContext: elevated
  description: Install 7-Zip via the winget package manager (DscV3.Discovery/WingetPackage).
resources:
  - name: 7-Zip
    type: Microsoft.DSC/PowerShell
    properties:
      resources:
        - name: Install 7-Zip
          type: DscV3.Discovery/WingetPackage
          properties:
            Id:     7zip.7zip
            Source: winget
            Ensure: Present
